Repository OCA/l10n-netherlands, pull requests merged in 2020-07, with the labels that each got.

#211 11.0 mig l10n nl dutch company type
  l10n_nl_dutch_company_type/README.rst
  l10n_nl_dutch_company_type/__init__.py
  l10n_nl_dutch_company_type/__manifest__.py
  l10n_nl_dutch_company_type/data/l10n_nl_dutch_company_type.xml
  l10n_nl_dutch_company_type/i18n/l10n_nl_dutch_company_type.pot
  l10n_nl_dutch_company_type/i18n/nl.po
  l10n_nl_dutch_company_type/readme/CONFIGURE.rst
  l10n_nl_dutch_company_type/readme/CONTRIBUTORS.rst
  l10n_nl_dutch_company_type/readme/DESCRIPTION.rst
  l10n_nl_dutch_company_type/readme/INSTALL.rst
  l10n_nl_dutch_company_type/static/description/icon.png
  l10n_nl_dutch_company_type/static/description/index.html
Labels: bot is merging ⏳, needs review

#208 [10.0][FIX] l10n_nl_cbs_export: backport of fixes
  l10n_nl_cbs_export/README.rst
  l10n_nl_cbs_export/__manifest__.py
  l10n_nl_cbs_export/models/cbs_export_file.py
  l10n_nl_cbs_export/readme/CONFIGURE.rst
  l10n_nl_cbs_export/readme/CONTRIBUTORS.rst
  l10n_nl_cbs_export/readme/CREDITS.rst
  l10n_nl_cbs_export/readme/DESCRIPTION.rst
  l10n_nl_cbs_export/readme/INSTALL.rst
  l10n_nl_cbs_export/readme/ROADMAP.rst
  l10n_nl_cbs_export/readme/USAGE.rst
  l10n_nl_cbs_export/tests/test_cbs_export_file.py
Labels: approved, bot is merging ⏳, needs review

#234 [12.0][MIG] l10n_nl_location_nuts
  l10n_nl_location_nuts/README.rst
  l10n_nl_location_nuts/__init__.py
  l10n_nl_location_nuts/__manifest__.py
  l10n_nl_location_nuts/hooks.py
  l10n_nl_location_nuts/i18n/l10n_nl_location_nuts.pot
  l10n_nl_location_nuts/readme/CONFIGURE.rst
  l10n_nl_location_nuts/readme/CONTRIBUTORS.rst
  l10n_nl_location_nuts/readme/DESCRIPTION.rst
  l10n_nl_location_nuts/static/description/icon.png
  l10n_nl_location_nuts/static/description/index.html
  l10n_nl_location_nuts/tests/__init__.py
  l10n_nl_location_nuts/tests/test_l10n_nl_location_nuts.py
  l10n_nl_location_nuts/wizard/__init__.py
  l10n_nl_location_nuts/wizard/nuts_import.py
  oca_dependencies.txt
Labels: bot is merging ⏳

#222 [FIX] suppress extra space if we've just a firstname
  l10n_nl_partner_name/model/res_partner.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#226 [FIX] l10n_nl_country_states. Be carefull with override of state_id.
  l10n_nl_country_states/models/res_partner.py
Labels: approved, bot is merging ⏳

#210 [MIG]11.0 mig l10n nl partner salutation
  l10n_nl_partner_salutation/README.rst
  l10n_nl_partner_salutation/__init__.py
  l10n_nl_partner_salutation/__manifest__.py
  l10n_nl_partner_salutation/data/res_partner_title.xml
  l10n_nl_partner_salutation/i18n/l10n_nl_partner_salutation.pot
  l10n_nl_partner_salutation/i18n/nl.po
  l10n_nl_partner_salutation/migrations/10.0.1.1.0/post-migration.py
  l10n_nl_partner_salutation/models/__init__.py
  l10n_nl_partner_salutation/models/res_partner.py
  l10n_nl_partner_salutation/models/res_partner_title.py
  l10n_nl_partner_salutation/tests/__init__.py
  l10n_nl_partner_salutation/tests/test_partner_salutation.py
  l10n_nl_partner_salutation/views/res_partner.xml
  l10n_nl_partner_salutation/views/res_partner_title.xml
Labels: approved, bot is merging ⏳, needs review

#246 [13.0][MIG] l10n_nl_location_nuts
  l10n_nl_location_nuts/README.rst
  l10n_nl_location_nuts/__init__.py
  l10n_nl_location_nuts/__manifest__.py
  l10n_nl_location_nuts/hooks.py
  l10n_nl_location_nuts/i18n/l10n_nl_location_nuts.pot
  l10n_nl_location_nuts/readme/CONFIGURE.rst
  l10n_nl_location_nuts/readme/CONTRIBUTORS.rst
  l10n_nl_location_nuts/readme/DESCRIPTION.rst
  l10n_nl_location_nuts/static/description/icon.png
  l10n_nl_location_nuts/static/description/index.html
  l10n_nl_location_nuts/tests/__init__.py
  l10n_nl_location_nuts/tests/test_l10n_nl_location_nuts.py
  l10n_nl_location_nuts/wizard/__init__.py
  l10n_nl_location_nuts/wizard/nuts_import.py
  l10n_nl_xaf_auditfile_export/models/xaf_auditfile_export.py
  oca_dependencies.txt
Labels: approved, bot is merging ⏳, ready to merge

#250 [12.0][FIX] l10n_nl_xaf_auditfile_export: avoid character / in filename
  l10n_nl_xaf_auditfile_export/models/xaf_auditfile_export.py
  l10n_nl_xaf_auditfile_export/tests/test_l10n_nl_xaf_auditfile_export.py
Labels: approved, bot is merging ⏳, ready to merge

#258 [11.0][IMP] l10n_nl_postcodeapi: mock tests
  .travis.yml
  l10n_nl_postcodeapi/tests/test_l10n_nl_postcodeapi.py
Labels: approved, bot is merging ⏳

#261 [13.0] l10n_nl_xaf_auditfile_export only posted moves
  l10n_nl_xaf_auditfile_export/models/xaf_auditfile_export.py
Labels: approved, bot is merging ⏳, ready to merge

#251 [MIG] [12.0] l10n_nl_partner_name
  l10n_nl_partner_name/README.rst
  l10n_nl_partner_name/__init__.py
  l10n_nl_partner_name/__manifest__.py
  l10n_nl_partner_name/data/ir.config_parameter.xml
  l10n_nl_partner_name/i18n/l10n_nl_partner_name.pot
  l10n_nl_partner_name/i18n/nl.po
  l10n_nl_partner_name/model/__init__.py
  l10n_nl_partner_name/model/res_partner.py
  l10n_nl_partner_name/scripts/guess_names.py
  l10n_nl_partner_name/static/description/icon.png
  l10n_nl_partner_name/static/src/img/icon.png
  l10n_nl_partner_name/tests/__init__.py
  l10n_nl_partner_name/tests/test_l10n_nl_partner_name.py
  l10n_nl_partner_name/views/res_partner.xml
  oca_dependencies.txt
Labels: approved, bot is merging ⏳, ready to merge

#241 [13.0][MIG] l10n_nl_postcode
  l10n_nl_postcode/README.rst
  l10n_nl_postcode/__init__.py
  l10n_nl_postcode/__manifest__.py
  l10n_nl_postcode/models/__init__.py
  l10n_nl_postcode/models/res_partner.py
  l10n_nl_postcode/readme/CONTRIBUTORS.rst
  l10n_nl_postcode/readme/DESCRIPTION.rst
  l10n_nl_postcode/readme/INSTALL.rst
  l10n_nl_postcode/readme/USAGE.rst
  l10n_nl_postcode/static/description/icon.png
  l10n_nl_postcode/static/description/index.html
  l10n_nl_postcode/tests/__init__.py
  l10n_nl_postcode/tests/test_l10n_nl_postcode.py
Labels: approved, bot is merging ⏳, ready to merge

#252 [MIG] l10n_nl_tax_invoice_basis: migration to 13.0
  .isort.cfg
  l10n_nl_tax_invoice_basis/README.rst
  l10n_nl_tax_invoice_basis/__init__.py
  l10n_nl_tax_invoice_basis/__manifest__.py
  l10n_nl_tax_invoice_basis/i18n/l10n_nl_tax_invoice_basis.pot
  l10n_nl_tax_invoice_basis/i18n/nl.po
  l10n_nl_tax_invoice_basis/models/__init__.py
  l10n_nl_tax_invoice_basis/models/account_move_line.py
  l10n_nl_tax_invoice_basis/models/account_tax.py
  l10n_nl_tax_invoice_basis/models/res_company.py
  l10n_nl_tax_invoice_basis/models/res_config_settings.py
  l10n_nl_tax_invoice_basis/readme/CONFIGURE.rst
  l10n_nl_tax_invoice_basis/readme/CREDITS.rst
  l10n_nl_tax_invoice_basis/readme/DESCRIPTION.rst
  l10n_nl_tax_invoice_basis/readme/INSTALL.rst
  l10n_nl_tax_invoice_basis/readme/ROADMAP.rst
  l10n_nl_tax_invoice_basis/readme/USAGE.rst
  l10n_nl_tax_invoice_basis/static/description/icon.png
  l10n_nl_tax_invoice_basis/static/description/index.html
  l10n_nl_tax_invoice_basis/tests/__init__.py
  l10n_nl_tax_invoice_basis/tests/test_tax_invoice_basis.py
  l10n_nl_tax_invoice_basis/views/res_config_settings.xml
  oca_dependencies.txt
  setup/l10n_nl_tax_invoice_basis/odoo/addons/l10n_nl_tax_invoice_basis
  setup/l10n_nl_tax_invoice_basis/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#267 [ADD] addons table in readme [ci skip]
  README.md
Labels: approved

#266 [ADD] addons table in readme
  README.md
Labels: approved

#265 [UPD] pin flake8 version [ci skip]
  .pre-commit-config.yaml
Labels: bot is merging ⏳
