Repository OCA/l10n-netherlands, pull requests merged in 2021-08, with the labels that each got.

#322 [14.0][FIX] l10n_nl_xaf_auditfile: Added Netherlands Antilles to Country and Currency Lists
  l10n_nl_xaf_auditfile_export/data/XmlAuditfileFinancieel3.2.xsd
Labels: approved, bot is merging ⏳, ready to merge

#269 [12.0][FIX] l10n_nl_xaf_auditfile_export: debit/credit in case no move lines found
  l10n_nl_xaf_auditfile_export/models/xaf_auditfile_export.py
Labels: approved, bot is merging ⏳

#274 [12.0][MIG] l10n_nl_kvk
  l10n_nl_kvk/README.rst
  l10n_nl_kvk/__init__.py
  l10n_nl_kvk/__manifest__.py
  l10n_nl_kvk/data/api_kvk_nl_bundle.crt
  l10n_nl_kvk/examples/kvk_68727720.json
  l10n_nl_kvk/examples/kvk_69599084.json
  l10n_nl_kvk/examples/kvk_90004760.json
  l10n_nl_kvk/i18n/l10n_nl_kvk.pot
  l10n_nl_kvk/models/__init__.py
  l10n_nl_kvk/models/l10n_nl_kvk_api_handler.py
  l10n_nl_kvk/models/res_config_settings.py
  l10n_nl_kvk/models/res_partner.py
  l10n_nl_kvk/readme/CONFIGURE.rst
  l10n_nl_kvk/readme/CONTRIBUTORS.rst
  l10n_nl_kvk/readme/DESCRIPTION.rst
  l10n_nl_kvk/readme/USAGE.rst
  l10n_nl_kvk/static/description/icon.png
  l10n_nl_kvk/static/description/index.html
  l10n_nl_kvk/tests/__init__.py
  l10n_nl_kvk/tests/test_l10n_nl_kvk.py
  l10n_nl_kvk/tests/test_partner_coc.py
  l10n_nl_kvk/views/res_config_settings.xml
  l10n_nl_kvk/views/res_partner.xml
  l10n_nl_kvk/wizards/__init__.py
  l10n_nl_kvk/wizards/l10n_nl_kvk_preview_wizard.py
  l10n_nl_kvk/wizards/l10n_nl_kvk_preview_wizard.xml
Labels: bot is merging ⏳

#320 [12.0][IMP] l10n_nl_vat_statement_icp_line: allow GB ICP lines before brexit
  l10n_nl_tax_statement_icp/models/l10n_nl_vat_statement_icp_line.py
Labels: approved, bot is merging ⏳

#287 [12.0] [MIG] l10n nl partner salutation
  l10n_nl_partner_salutation/README.rst
  l10n_nl_partner_salutation/__init__.py
  l10n_nl_partner_salutation/__manifest__.py
  l10n_nl_partner_salutation/data/res_partner_title.xml
  l10n_nl_partner_salutation/i18n/l10n_nl_partner_salutation.pot
  l10n_nl_partner_salutation/i18n/nl.po
  l10n_nl_partner_salutation/models/__init__.py
  l10n_nl_partner_salutation/models/res_partner.py
  l10n_nl_partner_salutation/models/res_partner_title.py
  l10n_nl_partner_salutation/readme/CONFIGURE.rst
  l10n_nl_partner_salutation/readme/CONTRIBUTORS.rst
  l10n_nl_partner_salutation/readme/DESCRIPTION.rst
  l10n_nl_partner_salutation/readme/USAGE.rst
  l10n_nl_partner_salutation/static/description/icon.png
  l10n_nl_partner_salutation/static/description/index.html
  l10n_nl_partner_salutation/tests/__init__.py
  l10n_nl_partner_salutation/tests/test_partner_salutation.py
  l10n_nl_partner_salutation/views/res_partner.xml
  l10n_nl_partner_salutation/views/res_partner_title.xml
Labels: bot is merging ⏳
