Repository OCA/l10n-netherlands, pull requests merged in 2021-09, with the labels that each got.

#335 [FIX] l10n_nl_tax_invoice_basis: Delete extra invoice.post
  l10n_nl_tax_invoice_basis/tests/test_tax_invoice_basis.py
Labels: approved, bot is merging ⏳

#275 [12.0][MIG] l10n_nl_openkvk
  l10n_nl_openkvk/README.rst
  l10n_nl_openkvk/__init__.py
  l10n_nl_openkvk/__manifest__.py
  l10n_nl_openkvk/examples/openkvk_560487.json
  l10n_nl_openkvk/examples/openkvk_56048785.json
  l10n_nl_openkvk/examples/openkvk_hoofdvestiging-56048785-0000-onestein-bv.json
  l10n_nl_openkvk/examples/openkvk_rechtspersoon-56048785-onestein-bv.json
  l10n_nl_openkvk/i18n/l10n_nl_openkvk.pot
  l10n_nl_openkvk/models/__init__.py
  l10n_nl_openkvk/models/l10n_nl_kvk_api_handler.py
  l10n_nl_openkvk/models/res_config_settings.py
  l10n_nl_openkvk/readme/CONFIGURE.rst
  l10n_nl_openkvk/readme/CONTRIBUTORS.rst
  l10n_nl_openkvk/readme/DESCRIPTION.rst
  l10n_nl_openkvk/readme/USAGE.rst
  l10n_nl_openkvk/static/description/icon.png
  l10n_nl_openkvk/static/description/index.html
  l10n_nl_openkvk/tests/__init__.py
  l10n_nl_openkvk/tests/test_l10n_nl_openkvk.py
  l10n_nl_openkvk/views/res_config_settings.xml
  l10n_nl_openkvk/wizards/__init__.py
  l10n_nl_openkvk/wizards/l10n_nl_kvk_preview_wizard.py
Labels: bot is merging ⏳

#268 [13.0][FIX] l10n_nl_bsn: search bsn with dots
  l10n_nl_bsn/models/res_partner.py
  l10n_nl_bsn/tests/test_l10n_nl_bsn.py
Labels: approved, ready to merge, bot is merging ⏳
