Repository OCA/l10n-netherlands, pull requests merged in 2021-03, with the labels that each got.

#306 [13.0][FIX] l10n_nl_xaf_auditfile_export: error bankAccNr length limit exceeded
  l10n_nl_xaf_auditfile_export/views/templates.xml
Labels: approved, bot is merging ⏳

#283 [14.0][MIG] l10n_nl_bsn
  l10n_nl_bsn/README.rst
  l10n_nl_bsn/__init__.py
  l10n_nl_bsn/__manifest__.py
  l10n_nl_bsn/i18n/l10n_nl_bsn.pot
  l10n_nl_bsn/i18n/nl.po
  l10n_nl_bsn/models/__init__.py
  l10n_nl_bsn/models/res_partner.py
  l10n_nl_bsn/readme/CONFIGURE.rst
  l10n_nl_bsn/readme/CONTRIBUTORS.rst
  l10n_nl_bsn/readme/DESCRIPTION.rst
  l10n_nl_bsn/readme/INSTALL.rst
  l10n_nl_bsn/readme/ROADMAP.rst
  l10n_nl_bsn/readme/USAGE.rst
  l10n_nl_bsn/static/description/icon.png
  l10n_nl_bsn/static/description/index.html
  l10n_nl_bsn/tests/__init__.py
  l10n_nl_bsn/tests/test_l10n_nl_bsn.py
  l10n_nl_bsn/views/res_partner.xml
Labels: approved, bot is merging ⏳, ready to merge

#286 [14.0][MIG] l10n_nl_account_tax_unece
  l10n_nl_account_tax_unece/README.rst
  l10n_nl_account_tax_unece/__init__.py
  l10n_nl_account_tax_unece/__manifest__.py
  l10n_nl_account_tax_unece/data/account_tax_template.xml
  l10n_nl_account_tax_unece/i18n/l10n_nl_account_tax_unece.pot
  l10n_nl_account_tax_unece/i18n/nl.po
  l10n_nl_account_tax_unece/models/__init__.py
  l10n_nl_account_tax_unece/models/res_company.py
  l10n_nl_account_tax_unece/post_install.py
  l10n_nl_account_tax_unece/readme/CONTRIBUTORS.rst
  l10n_nl_account_tax_unece/readme/CREDITS.rst
  l10n_nl_account_tax_unece/readme/DESCRIPTION.rst
  l10n_nl_account_tax_unece/readme/HISTORY.rst
  l10n_nl_account_tax_unece/readme/INSTALL.rst
  l10n_nl_account_tax_unece/readme/USAGE.rst
  l10n_nl_account_tax_unece/static/description/icon.png
  l10n_nl_account_tax_unece/static/description/index.html
  l10n_nl_account_tax_unece/tests/__init__.py
  l10n_nl_account_tax_unece/tests/test_nl_account_tax_unece.py
  oca_dependencies.txt
Labels: approved, bot is merging ⏳, ready to merge

#284 [14.0][MIG] l10n_nl_postcode
  l10n_nl_postcode/README.rst
  l10n_nl_postcode/__init__.py
  l10n_nl_postcode/__manifest__.py
  l10n_nl_postcode/i18n/l10n_nl_postcode.pot
  l10n_nl_postcode/models/__init__.py
  l10n_nl_postcode/models/res_partner.py
  l10n_nl_postcode/readme/CONTRIBUTORS.rst
  l10n_nl_postcode/readme/DESCRIPTION.rst
  l10n_nl_postcode/readme/INSTALL.rst
  l10n_nl_postcode/readme/USAGE.rst
  l10n_nl_postcode/static/description/icon.png
  l10n_nl_postcode/static/description/index.html
  l10n_nl_postcode/tests/__init__.py
  l10n_nl_postcode/tests/test_l10n_nl_postcode.py
Labels: approved, bot is merging ⏳, ready to merge

#307 [14.0][MIG] l10n_nl_bank
  l10n_nl_bank/README.rst
  l10n_nl_bank/__init__.py
  l10n_nl_bank/__manifest__.py
  l10n_nl_bank/data/res_bank_data.xml
  l10n_nl_bank/i18n/l10n_nl_bank.pot
  l10n_nl_bank/migrations/14.0.1.0.0/post-migration.py
  l10n_nl_bank/migrations/14.0.1.0.0/pre-migration.py
  l10n_nl_bank/readme/CONTRIBUTORS.rst
  l10n_nl_bank/readme/CREDITS.rst
  l10n_nl_bank/readme/DESCRIPTION.rst
  l10n_nl_bank/static/description/icon.png
  l10n_nl_bank/static/description/icon.svg
  l10n_nl_bank/static/description/index.html
  setup/l10n_nl_bank/odoo/addons/l10n_nl_bank
  setup/l10n_nl_bank/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#299 [13.0][UPD] Update res_bank_data.xml
  l10n_nl_bank/__manifest__.py
  l10n_nl_bank/data/res_bank_data.xml
  l10n_nl_bank/migrations/13.0.1.1.0/post-migration.py
  l10n_nl_bank/migrations/13.0.1.1.0/pre-migration.py
  l10n_nl_bank/readme/DESCRIPTION.rst
  l10n_nl_bank/static/description/icon.png
Labels: approved, bot is merging ⏳

#310 [12.0][IMP] l10n_nl_tax_statement: by default, don't include moves from before the earliest statement
  l10n_nl_tax_statement/models/account_move_line.py
  l10n_nl_tax_statement/models/l10n_nl_vat_statement.py
  l10n_nl_tax_statement/tests/test_l10n_nl_vat_statement.py
Labels: approved, bot is merging ⏳

#309 [13.0][FIX] l10n_nl_location_nuts: mocked tests
  .prettierignore
  l10n_nl_location_nuts/tests/test_l10n_nl_location_nuts.py
  l10n_nl_location_nuts/tests/vcr_cassettes/nuts_import.yaml
  requirements.txt
Labels: bot is merging ⏳
