Repository OCA/l10n-netherlands, pull requests merged in 2021-11, with the labels that each got.

#323 [14.0][FIX] l10n_nl_xaf_auditfile_export: Rounded move line amounts in template to avoid too many decimals error
  l10n_nl_xaf_auditfile_export/views/templates.xml
Labels: approved, ready to merge, bot is merging ⏳, stale

#338 [MIG][13.0] l10n_nl_mis_reports
  l10n_nl_mis_reports/README.rst
  l10n_nl_mis_reports/__init__.py
  l10n_nl_mis_reports/__manifest__.py
  l10n_nl_mis_reports/data/mis_report.xml
  l10n_nl_mis_reports/data/mis_report_kpi.xml
  l10n_nl_mis_reports/data/mis_report_style.xml
  l10n_nl_mis_reports/data/mis_report_subreport.xml
  l10n_nl_mis_reports/models/__init__.py
  l10n_nl_mis_reports/models/mis_report_instance.py
  l10n_nl_mis_reports/readme/CONTRIBUTORS.rst
  l10n_nl_mis_reports/readme/DESCRIPTION.rst
  l10n_nl_mis_reports/readme/ROADMAP.rst
  l10n_nl_mis_reports/readme/USAGE.rst
  l10n_nl_mis_reports/readme/newsfragments/.gitkeep
  l10n_nl_mis_reports/static/description/icon.png
  l10n_nl_mis_reports/static/description/index.html
  l10n_nl_mis_reports/static/src/css/l10n_nl_mis_reports.css
  l10n_nl_mis_reports/static/src/css/report.css
  l10n_nl_mis_reports/static/src/xml/l10n_nl_mis_reports.xml
  l10n_nl_mis_reports/tests/__init__.py
  l10n_nl_mis_reports/tests/test_l10n_nl_mis_reports.py
  l10n_nl_mis_reports/views/templates.xml
Labels: approved, bot is merging ⏳

#319 [13.0][FIX] l10n_nl_tax_statement: case no match on tags
  l10n_nl_tax_statement/models/l10n_nl_vat_statement.py
Labels: approved, ready to merge, bot is merging ⏳
