Repository OCA/l10n-netherlands, pull requests merged in 2022-04, with the labels that each got.

#346 [13.0] l10n_nl_xaf_auditfile_export: include lines from inactive journ…
  l10n_nl_xaf_auditfile_export/models/xaf_auditfile_export.py
  l10n_nl_xaf_auditfile_export/tests/test_l10n_nl_xaf_auditfile_export.py
Labels: approved, ready to merge, bot is merging ⏳

#260 [13.0][MIG] l10n_nl_tax_statement_icp
  l10n_nl_tax_statement_icp/README.rst
  l10n_nl_tax_statement_icp/__init__.py
  l10n_nl_tax_statement_icp/__manifest__.py
  l10n_nl_tax_statement_icp/i18n/l10n_nl_tax_statement_icp.pot
  l10n_nl_tax_statement_icp/models/__init__.py
  l10n_nl_tax_statement_icp/models/l10n_nl_vat_statement.py
  l10n_nl_tax_statement_icp/models/l10n_nl_vat_statement_icp_line.py
  l10n_nl_tax_statement_icp/readme/CONFIGURE.rst
  l10n_nl_tax_statement_icp/readme/CONTRIBUTORS.rst
  l10n_nl_tax_statement_icp/readme/DESCRIPTION.rst
  l10n_nl_tax_statement_icp/readme/ROADMAP.rst
  l10n_nl_tax_statement_icp/readme/USAGE.rst
  l10n_nl_tax_statement_icp/report/report_tax_statement.xml
  l10n_nl_tax_statement_icp/security/ir.model.access.csv
  l10n_nl_tax_statement_icp/static/description/icon.png
  l10n_nl_tax_statement_icp/static/description/index.html
  l10n_nl_tax_statement_icp/tests/__init__.py
  l10n_nl_tax_statement_icp/tests/test_l10n_nl_tax_statement_icp.py
  l10n_nl_tax_statement_icp/views/l10n_nl_vat_statement_view.xml
  l10n_nl_tax_statement_icp/views/report_tax_statement.xml
Labels: bot is merging ⏳

#347 [14.0] l10n_nl_xaf_auditfile_export: include lines from inactive journals
  l10n_nl_xaf_auditfile_export/models/xaf_auditfile_export.py
  l10n_nl_xaf_auditfile_export/tests/test_l10n_nl_xaf_auditfile_export.py
Labels: approved, ready to merge, bot is merging ⏳

#336 [12.0][MIG] l10n nl dutch company type
  l10n_nl_dutch_company_type/README.rst
  l10n_nl_dutch_company_type/__init__.py
  l10n_nl_dutch_company_type/__manifest__.py
  l10n_nl_dutch_company_type/data/l10n_nl_dutch_company_type.xml
  l10n_nl_dutch_company_type/i18n/l10n_nl_dutch_company_type.pot
  l10n_nl_dutch_company_type/i18n/nl.po
  l10n_nl_dutch_company_type/readme/CONFIGURE.rst
  l10n_nl_dutch_company_type/readme/CONTRIBUTORS.rst
  l10n_nl_dutch_company_type/readme/DESCRIPTION.rst
  l10n_nl_dutch_company_type/readme/INSTALL.rst
  l10n_nl_dutch_company_type/readme/USAGE.rst
  l10n_nl_dutch_company_type/static/description/icon.png
  l10n_nl_dutch_company_type/static/description/index.html
Labels: approved, migration, ready to merge, bot is merging ⏳

#332 [12.0][MIG] l10n nl country states
  l10n_nl_country_states/README.rst
  l10n_nl_country_states/__init__.py
  l10n_nl_country_states/__manifest__.py
  l10n_nl_country_states/data/l10n_nl_country_states.xml
  l10n_nl_country_states/data/res_country_state_nl_zip.xml
  l10n_nl_country_states/examples/generate_postcode_regios.py
  l10n_nl_country_states/examples/provincie.xls
  l10n_nl_country_states/i18n/l10n_nl_country_states.pot
  l10n_nl_country_states/i18n/nl.po
  l10n_nl_country_states/i18n/nl_NL.po
  l10n_nl_country_states/models/__init__.py
  l10n_nl_country_states/models/res_country_state_nl_zip.py
  l10n_nl_country_states/models/res_partner.py
  l10n_nl_country_states/readme/CONFIGURE.rst
  l10n_nl_country_states/readme/CONTRIBUTORS.rst
  l10n_nl_country_states/readme/CREDITS.rst
  l10n_nl_country_states/readme/DESCRIPTION.rst
  l10n_nl_country_states/security/ir.model.access.csv
  l10n_nl_country_states/static/description/icon.png
  l10n_nl_country_states/static/description/index.html
  l10n_nl_country_states/static/description/screenshot.png
  l10n_nl_country_states/tests/__init__.py
  l10n_nl_country_states/tests/test_l10n_nl_country_states.py
Labels: approved, ready to merge, bot is merging ⏳
