Repository OCA/l10n-netherlands, pull requests merged in 2022-10, with the labels that each got.

#362 [FIX] [12.0] l10n_nl_tax_statement: translation terms
  l10n_nl_tax_statement/i18n/nl.po
  l10n_nl_tax_statement/i18n/nl_NL.po
Labels: bot is merging ⏳

#361 [10.0][FIX] l10n_nl_tax_invoice_basis tests
  l10n_nl_tax_invoice_basis/tests/test_tax_invoice_basis.py
Labels: approved, ready to merge, bot is merging ⏳

#326 [14.0][FIX] XAF_auditfile_export: Solve opening balances mismatch problem
  l10n_nl_xaf_auditfile_export/models/xaf_auditfile_export.py
  l10n_nl_xaf_auditfile_export/tests/test_l10n_nl_xaf_auditfile_export.py
Labels: approved, bot is merging ⏳
