Repository OCA/l10n-netherlands, pull requests merged in 2023-10, with the labels that each got.

#394 [15.0][IMP] l10n_nl_tax_statement: add XLS export
  l10n_nl_tax_statement/__init__.py
  l10n_nl_tax_statement/__manifest__.py
  l10n_nl_tax_statement/readme/USAGE.rst
  l10n_nl_tax_statement/report/__init__.py
  l10n_nl_tax_statement/report/l10n_nl_tax_statement_xlsx.py
  l10n_nl_tax_statement/tests/test_l10n_nl_vat_statement.py
  l10n_nl_tax_statement/views/report_tax_statement.xml
Labels: approved, ready to merge, bot is merging ⏳

#400 [16.0][IMP] l10n_nl_tax_statement: refactor tests to increase coverage
  l10n_nl_tax_statement/tests/test_l10n_nl_vat_statement.py
Labels: approved, bot is merging ⏳

#220 [11.0][FIX] l10n_nl_tax_statement: add past invoices in report
  l10n_nl_tax_statement/__manifest__.py
  l10n_nl_tax_statement/models/account_tax.py
  l10n_nl_tax_statement/models/l10n_nl_vat_statement.py
  l10n_nl_tax_statement/models/l10n_nl_vat_statement_line.py
  l10n_nl_tax_statement/readme/ROADMAP.rst
Labels: approved

#399 [16.0][FWP] quicker validate, show traceback, keep faulty file, invalid chrs removal
  l10n_nl_xaf_auditfile_export/models/xaf_auditfile_export.py
  l10n_nl_xaf_auditfile_export/tests/test_l10n_nl_xaf_auditfile_export.py
  l10n_nl_xaf_auditfile_export/views/xaf_auditfile_export.xml
Labels: bot is merging ⏳
