Repository OCA/l10n-netherlands, pull requests merged in 2023-03, with the labels that each got.

#385 [14.0] update dotfiles
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: approved, bot is merging ⏳

#364 [15.0][MIG] l10n nl xaf auditfile export
  l10n_nl_xaf_auditfile_export/README.rst
  l10n_nl_xaf_auditfile_export/__init__.py
  l10n_nl_xaf_auditfile_export/__manifest__.py
  l10n_nl_xaf_auditfile_export/data/XmlAuditfileFinancieel3.2.xsd
  l10n_nl_xaf_auditfile_export/i18n/l10n_nl_xaf_auditfile_export.pot
  l10n_nl_xaf_auditfile_export/i18n/nl.po
  l10n_nl_xaf_auditfile_export/models/__init__.py
  l10n_nl_xaf_auditfile_export/models/ir_qweb.py
  l10n_nl_xaf_auditfile_export/models/xaf_auditfile_export.py
  l10n_nl_xaf_auditfile_export/readme/CONFIGURE.rst
  l10n_nl_xaf_auditfile_export/readme/CONTRIBUTORS.rst
  l10n_nl_xaf_auditfile_export/readme/CREDITS.rst
  l10n_nl_xaf_auditfile_export/readme/DESCRIPTION.rst
  l10n_nl_xaf_auditfile_export/readme/ROADMAP.rst
  l10n_nl_xaf_auditfile_export/readme/USAGE.rst
  l10n_nl_xaf_auditfile_export/security/ir.model.access.csv
  l10n_nl_xaf_auditfile_export/static/description/icon.png
  l10n_nl_xaf_auditfile_export/static/description/index.html
  l10n_nl_xaf_auditfile_export/tests/__init__.py
  l10n_nl_xaf_auditfile_export/tests/test_l10n_nl_xaf_auditfile_export.py
  l10n_nl_xaf_auditfile_export/views/menu.xml
  l10n_nl_xaf_auditfile_export/views/templates.xml
  l10n_nl_xaf_auditfile_export/views/xaf_auditfile_export.xml
  setup/l10n_nl_xaf_auditfile_export/odoo/addons/l10n_nl_xaf_auditfile_export
  setup/l10n_nl_xaf_auditfile_export/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳

#386 [16.0][MIG] l10n_nl_bank
  l10n_nl_bank/README.rst
  l10n_nl_bank/__init__.py
  l10n_nl_bank/__manifest__.py
  l10n_nl_bank/data/res_bank_data.xml
  l10n_nl_bank/i18n/l10n_nl_bank.pot
  l10n_nl_bank/readme/CONTRIBUTORS.rst
  l10n_nl_bank/readme/CREDITS.rst
  l10n_nl_bank/readme/DESCRIPTION.rst
  l10n_nl_bank/static/description/icon.png
  l10n_nl_bank/static/description/icon.svg
  l10n_nl_bank/static/description/index.html
  setup/l10n_nl_bank/odoo/addons/l10n_nl_bank
  setup/l10n_nl_bank/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#371 [16.0][MIG] l10n_nl_xaf_auditfile_export
  l10n_nl_xaf_auditfile_export/README.rst
  l10n_nl_xaf_auditfile_export/__init__.py
  l10n_nl_xaf_auditfile_export/__manifest__.py
  l10n_nl_xaf_auditfile_export/data/XmlAuditfileFinancieel3.2.xsd
  l10n_nl_xaf_auditfile_export/i18n/l10n_nl_xaf_auditfile_export.pot
  l10n_nl_xaf_auditfile_export/i18n/nl.po
  l10n_nl_xaf_auditfile_export/models/__init__.py
  l10n_nl_xaf_auditfile_export/models/ir_qweb.py
  l10n_nl_xaf_auditfile_export/models/xaf_auditfile_export.py
  l10n_nl_xaf_auditfile_export/readme/CONFIGURE.rst
  l10n_nl_xaf_auditfile_export/readme/CONTRIBUTORS.rst
  l10n_nl_xaf_auditfile_export/readme/CREDITS.rst
  l10n_nl_xaf_auditfile_export/readme/DESCRIPTION.rst
  l10n_nl_xaf_auditfile_export/readme/ROADMAP.rst
  l10n_nl_xaf_auditfile_export/readme/USAGE.rst
  l10n_nl_xaf_auditfile_export/security/ir.model.access.csv
  l10n_nl_xaf_auditfile_export/static/description/icon.png
  l10n_nl_xaf_auditfile_export/static/description/index.html
  l10n_nl_xaf_auditfile_export/tests/__init__.py
  l10n_nl_xaf_auditfile_export/tests/test_l10n_nl_xaf_auditfile_export.py
  l10n_nl_xaf_auditfile_export/views/menu.xml
  l10n_nl_xaf_auditfile_export/views/templates.xml
  l10n_nl_xaf_auditfile_export/views/xaf_auditfile_export.xml
  setup/l10n_nl_xaf_auditfile_export/odoo/addons/l10n_nl_xaf_auditfile_export
  setup/l10n_nl_xaf_auditfile_export/setup.py
Labels: approved, bot is merging ⏳

#387 [14.0] xaf_auditfile_export: improved selection of undivided profit account
  l10n_nl_xaf_auditfile_export/models/xaf_auditfile_export.py
Labels: approved, ready to merge, bot is merging ⏳
