Repository OCA/l10n-netherlands, pull requests merged in 2024-03, with the labels that each got.

#412 [FIX] l10n_nl_kvk: adapt tsts to changed demo data
  l10n_nl_kvk/tests/test_l10n_nl_kvk.py
Labels: bot is merging ⏳

#411 [12.0][ADD] l10n_nl_xaf_auditfile_export: opening balance support
  README.md
  l10n_nl_xaf_auditfile_export/README.rst
  l10n_nl_xaf_auditfile_export/__manifest__.py
  l10n_nl_xaf_auditfile_export/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#415 [16.0][ADD] l10n_nl_tax_statement: add chatter
  l10n_nl_tax_statement/models/l10n_nl_vat_statement.py
  l10n_nl_tax_statement/views/l10n_nl_vat_statement_view.xml
Labels: approved, bot is merging ⏳

#414 [12.0][ADD] l10n_nl_tax_statement: add chatter
  l10n_nl_tax_statement/models/l10n_nl_vat_statement.py
  l10n_nl_tax_statement/views/l10n_nl_vat_statement_view.xml
Labels: approved, bot is merging ⏳

#413 [16.0] l10n_nl_xaf_auditfile_export: correct opening balance, rounding
  l10n_nl_xaf_auditfile_export/models/xaf_auditfile_export.py
  l10n_nl_xaf_auditfile_export/tests/test_l10n_nl_xaf_auditfile_export.py
  l10n_nl_xaf_auditfile_export/views/templates.xml
Labels: approved, bot is merging ⏳

#404 [14.0][IMP][FIX] l10n_nl_account_tax_unece: Update account_tax_codes
  l10n_nl_account_tax_unece/README.rst
  l10n_nl_account_tax_unece/__manifest__.py
  l10n_nl_account_tax_unece/data/account_tax_template.xml
  l10n_nl_account_tax_unece/migrations/14.0.1.1.0/post-migration.py
  l10n_nl_account_tax_unece/models/res_company.py
  l10n_nl_account_tax_unece/readme/CONTRIBUTORS.rst
  l10n_nl_account_tax_unece/readme/HISTORY.rst
  l10n_nl_account_tax_unece/static/description/index.html
  l10n_nl_account_tax_unece/tests/test_nl_account_tax_unece.py
Labels: approved, bot is merging ⏳
